$terminal = ghostty
$fileManager = dolphin
$menu = rofi -show drun
$browser = firefox
$disable_logs = false
$enable_animations = yes
$mainMod = alt

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = ELECTRON_OZONE_PLATFORM_HINT,auto